source 'https://rubygems.org'


gem 'rails', '4.1.7'
gem 'pg'
gem 'rails_12factor', group: :development
gem 'devise'

gem 'sass-rails', '~> 4.0.3'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'

gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'spring',        group: :development

# debug
group :development do
	gem 'pry-rails'
	gem 'binding_of_caller'
	gem 'better_errors'
	gem 'pry'
	gem 'pry-byebug'
	gem 'thin'
end

gem 'annotate'