# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddb39e3f9f466b1506f1669aff7fb51380acbff2ee19678b6ec56da83c4a020b94915c9c2760e17aa40c752bbf8bbb9145fc5e19857b9d2fc7349b38b0184b5d

test:
  secret_key_base: 4f22a786944c879d78a4c00bcc43946acf2e1e02ff304caa2479eea6d5f2e7a050e15a952989eb399a6e26e92a85df05a9871ef6b412856e9e2be551927feb08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
