source 'https://rubygems.org'


# core 
gem 'rails', '4.1.5'
gem 'sqlite3'

# api
gem "rapgenius", "~> 1.0.2"

# front end
gem 'sass-rails', '~> 4.0.3'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'autoprefixer-rails'
gem 'simple_form'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'

gem 'spring',        group: :development

# debug
group :development do
	gem 'pry-rails'
	gem 'binding_of_caller'
	gem 'better_errors'
	gem 'pry'
	gem 'pry-byebug'
	gem 'thin'
end

# documentation
gem 'sdoc', '~> 0.4.0',          group: :doc

